// Shared city list for hotel destination autocomplete
// US cities show "City, ST" · International show "City, Country"

export const CITY_LIST = [
  // ── United States ──────────────────────────────────────────────
  { name: "New York",          sub: "NY" },
  { name: "Los Angeles",       sub: "CA" },
  { name: "Miami",             sub: "FL" },
  { name: "Chicago",           sub: "IL" },
  { name: "Las Vegas",         sub: "NV" },
  { name: "Orlando",           sub: "FL" },
  { name: "Dallas",            sub: "TX" },
  { name: "Houston",           sub: "TX" },
  { name: "Atlanta",           sub: "GA" },
  { name: "Denver",            sub: "CO" },
  { name: "Seattle",           sub: "WA" },
  { name: "San Francisco",     sub: "CA" },
  { name: "San Diego",         sub: "CA" },
  { name: "San Jose",          sub: "CA" },
  { name: "Sacramento",        sub: "CA" },
  { name: "Boston",            sub: "MA" },
  { name: "Phoenix",           sub: "AZ" },
  { name: "Tucson",            sub: "AZ" },
  { name: "Washington",        sub: "DC" },
  { name: "Nashville",         sub: "TN" },
  { name: "Memphis",           sub: "TN" },
  { name: "Tampa",             sub: "FL" },
  { name: "Fort Lauderdale",   sub: "FL" },
  { name: "Jacksonville",      sub: "FL" },
  { name: "Key West",          sub: "FL" },
  { name: "New Orleans",       sub: "LA" },
  { name: "Honolulu",          sub: "HI" },
  { name: "Maui",              sub: "HI" },
  { name: "Anchorage",         sub: "AK" },
  { name: "Philadelphia",      sub: "PA" },
  { name: "Pittsburgh",        sub: "PA" },
  { name: "Charlotte",         sub: "NC" },
  { name: "Raleigh",           sub: "NC" },
  { name: "Minneapolis",       sub: "MN" },
  { name: "Detroit",           sub: "MI" },
  { name: "Salt Lake City",    sub: "UT" },
  { name: "Portland",          sub: "OR" },
  { name: "Baltimore",         sub: "MD" },
  { name: "Kansas City",       sub: "MO" },
  { name: "St. Louis",         sub: "MO" },
  { name: "Indianapolis",      sub: "IN" },
  { name: "Columbus",          sub: "OH" },
  { name: "Cleveland",         sub: "OH" },
  { name: "Cincinnati",        sub: "OH" },
  { name: "San Antonio",       sub: "TX" },
  { name: "Austin",            sub: "TX" },
  { name: "Albuquerque",       sub: "NM" },
  { name: "Santa Fe",          sub: "NM" },
  { name: "Savannah",          sub: "GA" },
  { name: "Louisville",        sub: "KY" },
  { name: "Richmond",          sub: "VA" },
  { name: "Virginia Beach",    sub: "VA" },
  { name: "Oklahoma City",     sub: "OK" },
  { name: "Boise",             sub: "ID" },
  { name: "Omaha",             sub: "NE" },
  { name: "Buffalo",           sub: "NY" },
  // ── Canada ─────────────────────────────────────────────────────
  { name: "Toronto",           sub: "Ontario, Canada" },
  { name: "Vancouver",         sub: "BC, Canada" },
  { name: "Montreal",          sub: "Quebec, Canada" },
  { name: "Calgary",           sub: "Alberta, Canada" },
  { name: "Ottawa",            sub: "Ontario, Canada" },
  { name: "Quebec City",       sub: "Quebec, Canada" },
  { name: "Whistler",          sub: "BC, Canada" },
  // ── Mexico ─────────────────────────────────────────────────────
  { name: "Cancún",            sub: "Mexico" },
  { name: "Cabo San Lucas",    sub: "Mexico" },
  { name: "Puerto Vallarta",   sub: "Mexico" },
  { name: "Mexico City",       sub: "Mexico" },
  { name: "Playa del Carmen",  sub: "Mexico" },
  { name: "Tulum",             sub: "Mexico" },
  { name: "Oaxaca",            sub: "Mexico" },
  { name: "Guadalajara",       sub: "Mexico" },
  // ── Caribbean ──────────────────────────────────────────────────
  { name: "Punta Cana",        sub: "Dominican Republic" },
  { name: "Santo Domingo",     sub: "Dominican Republic" },
  { name: "Nassau",            sub: "Bahamas" },
  { name: "Freeport",          sub: "Bahamas" },
  { name: "Montego Bay",       sub: "Jamaica" },
  { name: "Kingston",          sub: "Jamaica" },
  { name: "Negril",            sub: "Jamaica" },
  { name: "San Juan",          sub: "Puerto Rico" },
  { name: "Aruba",             sub: "Aruba" },
  { name: "Curaçao",           sub: "Curaçao" },
  { name: "St. Maarten",       sub: "Caribbean" },
  { name: "St. Lucia",         sub: "Caribbean" },
  { name: "Barbados",          sub: "Caribbean" },
  { name: "Trinidad",          sub: "Caribbean" },
  { name: "Havana",            sub: "Cuba" },
  { name: "Varadero",          sub: "Cuba" },
  // ── Central / South America ────────────────────────────────────
  { name: "Panama City",       sub: "Panama" },
  { name: "San José",          sub: "Costa Rica" },
  { name: "Cartagena",         sub: "Colombia" },
  { name: "Medellín",          sub: "Colombia" },
  { name: "Bogotá",            sub: "Colombia" },
  { name: "Lima",              sub: "Peru" },
  { name: "Cusco",             sub: "Peru" },
  { name: "Buenos Aires",      sub: "Argentina" },
  { name: "Rio de Janeiro",    sub: "Brazil" },
  { name: "São Paulo",         sub: "Brazil" },
  { name: "Florianópolis",     sub: "Brazil" },
  // ── Europe ─────────────────────────────────────────────────────
  { name: "Paris",             sub: "France" },
  { name: "Nice",              sub: "France" },
  { name: "Lyon",              sub: "France" },
  { name: "Marseille",         sub: "France" },
  { name: "London",            sub: "England" },
  { name: "Manchester",        sub: "England" },
  { name: "Edinburgh",         sub: "Scotland" },
  { name: "Dublin",            sub: "Ireland" },
  { name: "Rome",              sub: "Italy" },
  { name: "Milan",             sub: "Italy" },
  { name: "Florence",          sub: "Italy" },
  { name: "Venice",            sub: "Italy" },
  { name: "Amalfi",            sub: "Italy" },
  { name: "Barcelona",         sub: "Spain" },
  { name: "Madrid",            sub: "Spain" },
  { name: "Seville",           sub: "Spain" },
  { name: "Ibiza",             sub: "Spain" },
  { name: "Málaga",            sub: "Spain" },
  { name: "Amsterdam",         sub: "Netherlands" },
  { name: "Lisbon",            sub: "Portugal" },
  { name: "Porto",             sub: "Portugal" },
  { name: "Algarve",           sub: "Portugal" },
  { name: "Athens",            sub: "Greece" },
  { name: "Santorini",         sub: "Greece" },
  { name: "Mykonos",           sub: "Greece" },
  { name: "Rhodes",            sub: "Greece" },
  { name: "Prague",            sub: "Czech Republic" },
  { name: "Vienna",            sub: "Austria" },
  { name: "Budapest",          sub: "Hungary" },
  { name: "Warsaw",            sub: "Poland" },
  { name: "Krakow",            sub: "Poland" },
  { name: "Reykjavik",         sub: "Iceland" },
  { name: "Copenhagen",        sub: "Denmark" },
  { name: "Stockholm",         sub: "Sweden" },
  { name: "Oslo",              sub: "Norway" },
  { name: "Bergen",            sub: "Norway" },
  { name: "Helsinki",          sub: "Finland" },
  { name: "Brussels",          sub: "Belgium" },
  { name: "Zurich",            sub: "Switzerland" },
  { name: "Geneva",            sub: "Switzerland" },
  { name: "Interlaken",        sub: "Switzerland" },
  { name: "Berlin",            sub: "Germany" },
  { name: "Munich",            sub: "Germany" },
  { name: "Frankfurt",         sub: "Germany" },
  { name: "Hamburg",           sub: "Germany" },
  { name: "Dubrovnik",         sub: "Croatia" },
  { name: "Split",             sub: "Croatia" },
  { name: "Tallinn",           sub: "Estonia" },
  { name: "Valletta",          sub: "Malta" },
  // ── Middle East / Africa ───────────────────────────────────────
  { name: "Dubai",             sub: "UAE" },
  { name: "Abu Dhabi",         sub: "UAE" },
  { name: "Doha",              sub: "Qatar" },
  { name: "Riyadh",            sub: "Saudi Arabia" },
  { name: "Tel Aviv",          sub: "Israel" },
  { name: "Jerusalem",         sub: "Israel" },
  { name: "Cairo",             sub: "Egypt" },
  { name: "Luxor",             sub: "Egypt" },
  { name: "Hurghada",          sub: "Egypt" },
  { name: "Marrakech",         sub: "Morocco" },
  { name: "Casablanca",        sub: "Morocco" },
  { name: "Cape Town",         sub: "South Africa" },
  { name: "Johannesburg",      sub: "South Africa" },
  { name: "Nairobi",           sub: "Kenya" },
  { name: "Zanzibar",          sub: "Tanzania" },
  { name: "Serengeti",         sub: "Tanzania" },
  // ── Asia / Pacific ─────────────────────────────────────────────
  { name: "Tokyo",             sub: "Japan" },
  { name: "Osaka",             sub: "Japan" },
  { name: "Kyoto",             sub: "Japan" },
  { name: "Okinawa",           sub: "Japan" },
  { name: "Bangkok",           sub: "Thailand" },
  { name: "Chiang Mai",        sub: "Thailand" },
  { name: "Phuket",            sub: "Thailand" },
  { name: "Koh Samui",         sub: "Thailand" },
  { name: "Bali",              sub: "Indonesia" },
  { name: "Jakarta",           sub: "Indonesia" },
  { name: "Lombok",            sub: "Indonesia" },
  { name: "Singapore",         sub: "Singapore" },
  { name: "Kuala Lumpur",      sub: "Malaysia" },
  { name: "Langkawi",          sub: "Malaysia" },
  { name: "Manila",            sub: "Philippines" },
  { name: "Cebu",              sub: "Philippines" },
  { name: "Boracay",           sub: "Philippines" },
  { name: "Seoul",             sub: "South Korea" },
  { name: "Busan",             sub: "South Korea" },
  { name: "Beijing",           sub: "China" },
  { name: "Shanghai",          sub: "China" },
  { name: "Hong Kong",         sub: "Hong Kong" },
  { name: "Taipei",            sub: "Taiwan" },
  { name: "Mumbai",            sub: "India" },
  { name: "New Delhi",         sub: "India" },
  { name: "Goa",               sub: "India" },
  { name: "Jaipur",            sub: "India" },
  { name: "Agra",              sub: "India" },
  { name: "Maldives",          sub: "Maldives" },
  { name: "Colombo",           sub: "Sri Lanka" },
  { name: "Kathmandu",         sub: "Nepal" },
  { name: "Yangon",            sub: "Myanmar" },
  { name: "Hanoi",             sub: "Vietnam" },
  { name: "Ho Chi Minh City",  sub: "Vietnam" },
  { name: "Da Nang",           sub: "Vietnam" },
  { name: "Hoi An",            sub: "Vietnam" },
  { name: "Phnom Penh",        sub: "Cambodia" },
  { name: "Siem Reap",         sub: "Cambodia" },
  { name: "Sydney",            sub: "Australia" },
  { name: "Melbourne",         sub: "Australia" },
  { name: "Brisbane",          sub: "Australia" },
  { name: "Cairns",            sub: "Australia" },
  { name: "Gold Coast",        sub: "Australia" },
  { name: "Auckland",          sub: "New Zealand" },
  { name: "Queenstown",        sub: "New Zealand" },
  { name: "Christchurch",      sub: "New Zealand" },
];

// Returns "City, ST" or "City, Country"
export function cityLabel(city) {
  return `${city.name}, ${city.sub}`;
}

// Filter cities by typed input — starts-with first, then contains
export function filterCities(input, max = 7) {
  if (!input || input.length < 1) return [];
  const lower = input.toLowerCase();
  const startsWith = CITY_LIST.filter(c => c.name.toLowerCase().startsWith(lower));
  if (startsWith.length >= max) return startsWith.slice(0, max);
  const rest = CITY_LIST.filter(c =>
    !c.name.toLowerCase().startsWith(lower) &&
    (c.name.toLowerCase().includes(lower) || c.sub.toLowerCase().includes(lower))
  );
  return [...startsWith, ...rest].slice(0, max);
}
